### PR TITLE
[fix]:Added statefulset yaml to deploy dope

### PR DESCRIPTION
**Pull request by amitbhatt818**
Signed-off-by: Amit Bhatt <amitbhatt818@gmail.com>

- This PR adds statefulset yml which will help in deploying dope.

### CODE REVIEW

**Comment by AmitKumarDas** [comment]
thanks @amitbhatt818 
Can we keep the crd, rbac in manifests folder?
https://github.com/mayadata-io/d-operators/blob/master/test/setup/controlplane/setup.yaml depends on them.

**Comment by amitbhatt818** [comment]
> thanks @amitbhatt818
> Can we keep the crd, rbac in manifests folder?
> https://github.com/mayadata-io/d-operators/blob/master/test/setup/controlplane/setup.yaml depends on them.
Ok @AmitKumarDas

**Comment by amitbhatt818** [comment]
> Thanks @amitbhatt818 Have given a comment

Resolved comments PTAL @AmitKumarDas

**Pull request merged**
